CREATE TABLE IF NOT EXISTS persons (
	id          INTEGER  PRIMARY KEY AUTOINCREMENT,
	first_name  TEXT     NOT NULL,
	middle_name TEXT     DEFAULT NULL,
	last_name   TEXT     DEFAULT NULL,
	created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
	id           INTEGER  PRIMARY KEY AUTOINCREMENT,
	value        TEXT     NOT NULL,
	contact_type INTEGER  NOT NULL,
	is_main      INTEGER  NOT NULL CHECK(is_main IN (0, 1)),
	created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	person_id    INTEGER  NOT NULL,
	FOREIGN KEY (person_id) REFERENCES persons(id) 
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
	id          INTEGER  PRIMARY KEY AUTOINCREMENT,
	subject     TEXT     NOT NULL,
	description TEXT     DEFAULT NULL,
	status      INTEGER  NOT NULL,
	price       INTEGER  NOT NULL DEFAULT 0 CHECK(price >= 0),
	due         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS detail_tasks (
	id      INTEGER PRIMARY KEY AUTOINCREMENT,
	task_id INTEGER NOT NULL,
	FOREIGN KEY (task_id) REFERENCES tasks(id)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
	id            INTEGER  PRIMARY KEY AUTOINCREMENT,
	status        INTEGER  NOT NULL,
	order_date    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	total_price   INTEGER  NOT NULL DEFAULT 0 CHECK(total_price >= 0),
	person_id     INTEGER  NOT NULL,
	FOREIGN KEY (person_id) REFERENCES persons(id)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
	id            INTEGER  PRIMARY KEY AUTOINCREMENT,
	timestamp     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status        INTEGER  NOT NULL,
	method        INTEGER  NOT NULL,
	amount        INTEGER  NOT NULL DEFAULT 0 CHECK(amount >= 0),
	evidence_path TEXT     NOT NULL,
	order_id      INTEGER  NOT NULL,
	FOREIGN KEY (order_id) REFERENCES orders(id)
	ON DELETE CASCADE ON UPDATE CASCADE
);